# Generated by Django 4.2.7 on 2023-11-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='soura',
        ),
        migrations.RemoveField(
            model_name='student',
            name='next_amount',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Soura',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
