# Generated by Django 4.2.7 on 2023-11-23 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importData', '0004_remove_part_soura_remove_student_next_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Soura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hijri_year', models.CharField(max_length=4)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(upload_to='photos/students')),
                ('active', models.BooleanField(default=True)),
                ('next_amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='importData.part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='soura',
            field=models.ManyToManyField(null=True, to='importData.soura'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='importData.part')),
                ('soura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_soura', to='importData.soura')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='importData.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='importData.year')),
            ],
        ),
    ]
