# Generated by Django 4.2.7 on 2023-12-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0006_student_isfinished'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ahkam',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
