# Generated by Django 4.2.7 on 2023-12-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0008_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
