# Generated by Django 4.2.7 on 2023-12-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0009_remove_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.IntegerField(max_length=2),
        ),
    ]
