# Generated by Django 4.2.7 on 2024-04-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0011_alter_grade_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='fromBaqra',
            new_name='from_baqra',
        ),
    ]
