# Generated by Django 4.2.7 on 2024-10-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0013_alter_part_number_alter_part_soura'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_amount', to='importData.part'),
        ),
    ]
