# Generated by Django 4.2.7 on 2024-10-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0014_student_last_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['student', 'year']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_amount',
        ),
        migrations.AddField(
            model_name='student',
            name='last_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_part', to='importData.part'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_soura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='importData.soura'),
        ),
    ]
