# Generated by Django 4.2.7 on 2024-10-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0016_student_last_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isExamine',
            field=models.BooleanField(default=True),
        ),
    ]
