# Generated by Django 6.0 on 2025-12-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0017_student_isexamine'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
