# Generated by Django 6.0 on 2025-12-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0018_part_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
