# Generated by Django 6.0 on 2025-12-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0019_alter_part_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='active',
        ),
    ]
