# Generated by Django 4.2.7 on 2024-04-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('importData', '0013_alter_part_number_alter_part_soura'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=20)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='importData.part')),
                ('soura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_student_soura', to='importData.soura')),
            ],
        ),
    ]
