# Generated by Django 4.2.7 on 2024-05-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewStudent',
        ),
    ]
