# Generated by Django 4.2.7 on 2024-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='newStudent',
            field=models.BooleanField(default=False),
        ),
    ]
