# Generated by Django 4.2.7 on 2024-06-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_rename_new_student_newstudent_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='from_baqra',
            field=models.BooleanField(default=False),
        ),
    ]
