# Generated by Django 4.2.7 on 2024-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_rename_new_student_newstudent_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newstudent',
            name='prize_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
