# Generated by Django 4.2.7 on 2024-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_newstudent_from_baqra'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='prize_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
