# Generated by Django 4.2.7 on 2024-06-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_newstudent_grade_newstudent_prize_time'),
        ('registration', '0009_newstudent_grade'),
    ]

    operations = [
    ]
