# Generated by Django 6.0 on 2026-02-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importData', '0021_part_active'),
        ('registration', '0011_alter_newstudent_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='next_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_amount', to='importData.part'),
        ),
    ]
